name: '@actalog/node-template'
description: Template for Node Actions
author: Gabriel Rufino <contato@gabrielrufino.com>
branding:
  icon: check-square
  color: green

inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'

runs:
  using: 'node20'
  main: 'dist/index.js'
